export const INIT_GAME = 'init_game'
export const GAME_ADDED = 'game_added'
export const JOIN_ROOM = 'join_room'
export const OPPONENT_DISCONNECTED = 'opponent_disconnected'
export const GAME_JOINED = 'game_joined'
export const GAME_ENDED = 'game_ended'
export const GAME_ALERT = 'game_alert'
export const GAME_TIME = 'game_time'
export const EXIT_GAME = 'exit_game'

export const CREATE_GAME = 'create_game'
export const JOIN_GAME = 'join_game'
export const LEAVE_GAME = 'leave_game'

export const MOVE = 'move'
export const GAME_OVER = 'game_over'
export const RESIGN = 'resign'
export const DRAW_OFFER = 'draw_offer'
export const DRAW_RESPONSE = 'draw_response'

export const SEND_MESSAGE = 'send_message'
export const RECEIVE_MESSAGE = 'receive_message'